spring:

  application:
    name: framegenesis-ai

  datasource:
    url: jdbc:postgresql://localhost:5432/framegenesis_ai
    username: postgres
    password: postgres007

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: framegenesis-ai-ultra-secure-jwt-secret-key-2026

gemini:
  api:
    key: YOUR_GEMINI_API_KEY
    model: gemini-2.5-flash